name: Build node.js

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  NODE_VERSION: '18'   
  
# Allow one concurrent deployment
concurrency:
  group: 'server'
  cancel-in-progress: true

jobs:
  build-assets:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    # Setup Node
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    # Run npm build
    - name: npm install, build
      run: |        
        cd server && npm install
        node server/index.js